### ISSUE TITLE
Haruna seems to be using quite a bit more cpu power than mpv.

### ISSUE THREAD

**Issue by d-air1** [g-fb/haruna#63] opened 2021-04-02 06:01 UTC
I was testing by playing the same youtube video using mpv by itself and then using haruna.
![mpv-resources](https://user-images.githubusercontent.com/40647198/113385774-61a70500-934e-11eb-86d9-ebb08e35921c.png)

![haruna-resources](https://user-images.githubusercontent.com/40647198/113385779-67044f80-934e-11eb-8ddd-a164555ec304.png)

The haruna process on its on is about 3 to 4 times as much cpu power than just mpv at any given instance.

**Comment by g-fb** [comment] 2021-05-07 16:22
Haruna has joined KDE and has moved to https://invent.kde.org/multimedia/haruna.
Consider moving this to [bugs.kde.org](https://bugs.kde.org/enter_bug.cgi?product=Haruna&component=generic), to get notified about progress.
I'll move it myself, in a few days/weeks, if not done yet.

**Comment by g-fb** [comment] 2021-05-10 19:02
https://bugs.kde.org/show_bug.cgi?id=436886

I can't reproduce. Please provide more info, like a sample video and whether you use hardware decoding.
This repo will be archived soon so do it [here](https://bugs.kde.org/show_bug.cgi?id=436886).

**Closed as completed by g-fb** 2021-05-10 19:02 UTC
